version: '3.8'
services:
  spy:
    container_name: spy
    build:
      context: .
      dockerfile: ./docker/schemaspy/Dockerfile
    image: schemaspy/schemaspy
    tty: true
    volumes:
      - ./output:/output
      - ./schemaspy.properties.template:/schemaspy.properties.template
      - ./drivers/postgresql-42.6.0.jar:/drivers/postgresql.jar
    env_file:
      - .env
    networks:
      - schemaspy-sample

  nginx_schemaspy:
    container_name: "nginx_schemaspy"
    image: nginx
    depends_on:
      - spy
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html
    networks:
      - schemaspy-sample

networks:
  schemaspy-sample:
    driver: bridge
